### ISSUE TITLE
command line support

### ISSUE THREAD

**Issue by TheMakerOfWorlds** [Captain-FLAM/KaraFan#1]
Hey! is there a way to use this like I can use demucs, just by running it in the command line?

**Comment by Captain-FLAM** [comment]
I started with, but many people told me that they don't use it ...
So, I give up (because, it was less maintenance)
But, I let the code in place for a future version (maybe).

**Comment by TheMakerOfWorlds** [comment]
ok, thank you for getting back captain 🫡 I will have a look at the code for it

**Comment by Captain-FLAM** [comment]
Finally ...

I think it's getting harder and harder to manage complex parameters from command line,
and too much check for input errors from users.
So I decide to remove this option, but ...

I plan for KaraFan version 5.0 to add a GUI with wxwigets that will give you the ability to use it with not installing Visual Studio Code and can be run easily on your PC ! 😃

**Comment by Captain-FLAM** [comment]
I close this issue as **KaraFan 5.0** is also a stand-alone GUI now !

Still can be used in Colab.
