### ISSUE TITLE
Command terminal pop-ups when running KaraFan 5.1

### ISSUE THREAD

**Issue by RavenV-tiff** [Captain-FLAM/KaraFan#4]
When running KaraFan 5.1 there is a pop-up command terminal instance every second that prevents me from navigating windows explorer or other applications. Seems to be a new behavior after the update introduced a real-time progress bar.

There is a possibility that Microsoft Visual C++ 2015-2019 (x64) is the issue. I could not install this older version from the Setup.py so I removed it from the script to finish the install. Otherwise there's no issues separating tracks, but the pop-ups make KaraFan 5.1 unusable for me otherwise.

**Comment by Captain-FLAM** [comment]
Not sure to understand ?
Can you post a screenshot ?

**Comment by Captain-FLAM** [comment]
Fixed with 5.1.2
